<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // KAOS
            [
                'name' => 'Gradient Graphic T-shirt',
                'description' => 'T-shirt with vibrant gradient graphic design, perfect for casual wear',
                'category' => 'kaos',
                'subcategory' => 'lengan pendek',
                'price' => 60000,
                'original_price' => 80000,
                'image' => 'https://i.pinimg.com/1200x/3e/6b/f5/3e6bf5378b6ae4d43263dfb626d37588.jpg',
                'colors' => ['white', 'pink', 'blue'],
                'sizes' => ['Small', 'Medium', 'Large', 'X-Large'],
                'stock' => 50,
                'views' => 120,
                'sales' => 25,
                'is_featured' => true,
            ],
            [
                'name' => 'Polo with Tipping Details',
                'description' => 'Classic polo shirt with elegant tipping details on collar',
                'category' => 'kaos',
                'subcategory' => 'lengan pendek',
                'price' => 60000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/736x/45/4c/92/454c92dc87e9774bed336c9ea9d132ed.jpg',
                'colors' => ['red', 'purple', 'blue'],
                'sizes' => ['Medium', 'Large', 'X-Large'],
                'stock' => 40,
                'views' => 95,
                'sales' => 18,
                'is_featured' => false,
            ],
            [
                'name' => 'Black Striped T-shirt',
                'description' => 'Modern black and white striped t-shirt with raglan sleeves',
                'category' => 'kaos',
                'subcategory' => 'lengan pendek',
                'price' => 55000,
                'original_price' => 70000,
                'image' => 'https://i.pinimg.com/736x/4f/7e/bf/4f7ebfdc234afefe71d5f4a8ec8ba408.jpg',
                'colors' => ['black', 'white'],
                'sizes' => ['Small', 'Medium', 'Large'],
                'stock' => 35,
                'views' => 88,
                'sales' => 22,
                'is_featured' => true,
            ],
            [
                'name' => 'Sleeve Striped T-shirt',
                'description' => 'Comfortable t-shirt with striped sleeve details',
                'category' => 'kaos',
                'subcategory' => 'lengan pendek',
                'price' => 45000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/736x/69/92/5a/69925a28d7d2cbb1caacb62ad74c4206.jpg',
                'colors' => ['black', 'orange', 'yellow'],
                'sizes' => ['Small', 'Medium', 'Large', 'X-Large'],
                'stock' => 60,
                'views' => 142,
                'sales' => 35,
                'is_featured' => false,
            ],
            [
                'name' => 'Formal Shirt Green',
                'description' => 'Elegant formal shirt in green stripes',
                'category' => 'kaos',
                'subcategory' => 'lengan panjang',
                'price' => 80000,
                'original_price' => 100000,
                'image' => 'https://i.pinimg.com/736x/80/e1/c7/80e1c79f5a22e663bf5b5507e9ef293c.jpg',
                'colors' => ['green', 'white'],
                'sizes' => ['Medium', 'Large', 'X-Large'],
                'stock' => 25,
                'views' => 76,
                'sales' => 12,
                'is_featured' => false,
            ],
            [
                'name' => 'Orange Graphic T-shirt',
                'description' => 'Bold orange t-shirt with unique graphic design',
                'category' => 'kaos',
                'subcategory' => 'lengan pendek',
                'price' => 65000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/1200x/e1/4f/84/e14f84017368f18fba24c18f4da36fef.jpg',
                'colors' => ['orange', 'black'],
                'sizes' => ['Small', 'Medium', 'Large', 'X-Large'],
                'stock' => 45,
                'views' => 102,
                'sales' => 28,
                'is_featured' => true,
            ],
            [
                'name' => 'Plaid Casual Shirt',
                'description' => 'Comfortable plaid pattern casual shirt',
                'category' => 'kaos',
                'subcategory' => 'lengan panjang',
                'price' => 75000,
                'original_price' => 95000,
                'image' => 'https://i.pinimg.com/1200x/fd/20/e2/fd20e257b019babc8014be0dea3766c6.jpg',
                'colors' => ['red', 'blue', 'white'],
                'sizes' => ['Medium', 'Large', 'X-Large', '2X-Large'],
                'stock' => 30,
                'views' => 68,
                'sales' => 15,
                'is_featured' => false,
            ],
            
            // TOPI
            [
                'name' => 'Popular Baseball Cap',
                'description' => 'Classic baseball cap with adjustable strap',
                'category' => 'topi',
                'subcategory' => null,
                'price' => 100000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/1200x/e1/4f/84/e14f84017368f18fba24c18f4da36fef.jpg',
                'colors' => ['black', 'blue', 'red', 'white'],
                'sizes' => ['One Size'],
                'stock' => 80,
                'views' => 156,
                'sales' => 42,
                'is_featured' => true,
            ],
            [
                'name' => 'Snapback Cap Street Style',
                'description' => 'Modern snapback cap for street fashion',
                'category' => 'topi',
                'subcategory' => null,
                'price' => 85000,
                'original_price' => 110000,
                'image' => 'https://i.pinimg.com/1200x/e5/89/6c/e5896cd98ae66ee8580699d0425d1dd5.jpg',
                'colors' => ['black', 'yellow', 'blue'],
                'sizes' => ['One Size'],
                'stock' => 65,
                'views' => 134,
                'sales' => 38,
                'is_featured' => false,
            ],
            
            // JAKET
            [
                'name' => 'Casual Bomber Jacket',
                'description' => 'Stylish bomber jacket for casual occasions',
                'category' => 'jaket',
                'subcategory' => null,
                'price' => 180000,
                'original_price' => 220000,
                'image' => 'https://i.pinimg.com/736x/2f/85/1a/2f851aebd8b3fac0b0dd60d304dd1578.jpg',
                'colors' => ['green', 'black', 'blue'],
                'sizes' => ['Small', 'Medium', 'Large', 'X-Large'],
                'stock' => 20,
                'views' => 92,
                'sales' => 16,
                'is_featured' => true,
            ],
            [
                'name' => 'Denim Jacket Classic',
                'description' => 'Timeless denim jacket in classic blue',
                'category' => 'jaket',
                'subcategory' => null,
                'price' => 150000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/1200x/e5/89/6c/e5896cd98ae66ee8580699d0425d1dd5.jpg',
                'colors' => ['blue', 'black'],
                'sizes' => ['Medium', 'Large', 'X-Large'],
                'stock' => 18,
                'views' => 78,
                'sales' => 11,
                'is_featured' => false,
            ],
            
            // JERSEY
            [
                'name' => 'Football Jersey Pro',
                'description' => 'Professional football jersey with breathable fabric',
                'category' => 'jersey',
                'subcategory' => null,
                'price' => 120000,
                'original_price' => 150000,
                'image' => 'https://i.pinimg.com/originals/e9/04/53/e904533ed00df550bb4fc87064217f18.png',
                'colors' => ['red', 'blue', 'white', 'black'],
                'sizes' => ['Small', 'Medium', 'Large', 'X-Large', '2X-Large'],
                'stock' => 55,
                'views' => 168,
                'sales' => 48,
                'is_featured' => true,
            ],
            [
                'name' => 'Basketball Jersey',
                'description' => 'Cool basketball jersey for sports enthusiasts',
                'category' => 'jersey',
                'subcategory' => null,
                'price' => 110000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/1200x/3e/6b/f5/3e6bf5378b6ae4d43263dfb626d37588.jpg',
                'colors' => ['orange', 'purple', 'green'],
                'sizes' => ['Medium', 'Large', 'X-Large'],
                'stock' => 42,
                'views' => 124,
                'sales' => 31,
                'is_featured' => false,
            ],
            
            // TAS
            [
                'name' => 'Backpack Urban Style',
                'description' => 'Modern backpack with multiple compartments',
                'category' => 'tas',
                'subcategory' => null,
                'price' => 200000,
                'original_price' => 250000,
                'image' => 'https://i.pinimg.com/1200x/fd/20/e2/fd20e257b019babc8014be0dea3766c6.jpg',
                'colors' => ['black', 'blue', 'green'],
                'sizes' => ['One Size'],
                'stock' => 28,
                'views' => 145,
                'sales' => 36,
                'is_featured' => true,
            ],
            [
                'name' => 'Tote Bag Canvas',
                'description' => 'Eco-friendly canvas tote bag for everyday use',
                'category' => 'tas',
                'subcategory' => null,
                'price' => 75000,
                'original_price' => null,
                'image' => 'https://i.pinimg.com/736x/2f/85/1a/2f851aebd8b3fac0b0dd60d304dd1578.jpg',
                'colors' => ['white', 'black', 'yellow'],
                'sizes' => ['One Size'],
                'stock' => 70,
                'views' => 98,
                'sales' => 29,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
